"""NewsDigest ORM model – stores periodic AI-generated news summaries.

Each row represents one time-period digest (e.g. morning 08:30, midday 12:00).
The digest content is Markdown generated by DeepSeek, summarizing all news
published within that period.

Unique constraint on (digest_date, period_label) prevents duplicate digests.
"""

from datetime import date, datetime

from sqlalchemy import Date, DateTime, Index, Integer, String, Text, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class NewsDigest(Base):
    __tablename__ = "news_digests"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # 日期（按天索引，方便前端按天查询）
    digest_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)

    # 时段标签：morning / midday / evening / night
    period_label: Mapped[str] = mapped_column(String(32), nullable=False)

    # 时间段起止（带时区的完整时间戳，用于展示和调试）
    period_start: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    period_end: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    # 该时段收录的新闻数量
    news_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # DeepSeek 生成的总结内容（Markdown 格式）
    content: Mapped[str] = mapped_column(Text, nullable=False, default="")

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    __table_args__ = (
        # 同一天同一时段不重复
        UniqueConstraint("digest_date", "period_label", name="uq_digest_date_period"),
        # 前端查询：按日期倒序
        Index("ix_news_digests_date_desc", digest_date.desc()),
    )
