"""add_reports_table

Revision ID: fd0f8570cdf0
Revises: 1fc3903986cd
Create Date: 2026-02-12 22:08:55.091021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0f8570cdf0'
down_revision: Union[str, Sequence[str], None] = '1fc3903986cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_id', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('cover', sa.String(length=2048), nullable=True),
    sa.Column('summary', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sync_id')
    )
    op.create_index(op.f('ix_reports_date'), 'reports', ['date'], unique=False)
    op.create_index('ix_reports_date_desc', 'reports', [sa.literal_column('date DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reports_date_desc', table_name='reports')
    op.drop_index(op.f('ix_reports_date'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
